name: CI
on:
  push:
  pull_request:
env:
  CARGO_TERM_COLOR: always
jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Rust
        run: rustup update stable

      - name: Build project
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
