name: CI
on:
  push:
  pull_request:
env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
jobs:
  main:
    name: Build, test and lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Rust
        run: rustup update stable

      - name: Build project
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Run linter
        run: cargo clippy --all-targets --all-features

      - name: Check formatting
        run: cargo fmt --all --check
